#!/usr/bin/env python

import fileOps as fo
odat = fo.readFile("inputs/olcao.dat")
for i in range(len(odat)):
    if odat[i][0] == "XC_CODE":
        odat[i+1][0] = "990"
        break
fo.writeFile("inputs/olcao.dat", odat)

